;; defining tile-world domain

(define (domain tile-world)
  (:requirements :equality :typing )
  ;; These additional requirements may be necessary
  ;;(:requirements :equality :typing :adl :derived-predicates)
  (:types type thing location direction number color - object)
  (:predicates (floor ?l - location)
               (at ?l - location)
               (chip ?l - location)
               (socket ?l - location)
               (wall ?l - location)
               (block ?l - location)
               (bomb ?l - location)
               (popup-wall ?l - location)
               (dirt ?l - location)
               (gravel ?l - location)
               (thief ?l - location)
               (has-keys ?c - color ?n - number)
               (key ?l - location ?c - color)
               (door ?l - location ?c - color)
               (has-boots ?t - type)
               (boots ?l - location ?t - type)
               (force-floor ?l - location)
               (slide-dir ?l - location ?d - direction)
               (ice ?l - location)
               (ice-wall ?l - location)
               (ice-wall-dir ?l - location ?in - direction ?out - direction)
               (switch-wall-open ?l - location)
               (switch-wall-closed ?l - location)
               (switched-walls-open ?x - number )
               (successor ?n1 - number ?n0 - number)
               (chips-left ?n - number)
               (MOVE-DIR ?from ?to - location ?dir - direction))

  (:action move-floor
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (floor ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (not (chip-state slipping))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      )
   )
   
  (:action move-dirt
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (dirt ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (not (chip-state slipping))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (dirt ?to))
                      (floor ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      )
   )

  (:action move-thief
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (thief ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (not (chip-state slipping))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      (not (has-boots ice))
                      (not (has-boots water))
                      (not (has-boots fire))
                      (not (has-boots slide))
                      )
   )

  (:action move-popup-wall
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (popup-wall ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (not (chip-state slipping))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (popup-wall ?to))
                      (wall ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      )
   )
   
  (:action push-block
   :parameters (?from ?to - location ?dir - direction ?blockto - location)
   :precondition (and (at ?from)
                      (block ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (MOVE-DIR ?to ?blockto ?dir)
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (not (chip-state slipping)) ;does this matter?
                      (floor ?blockto)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (block ?to))
                      (block ?blockto)
                      (floor ?to)
                      (not (floor ?blockto))
                      (not (chip-state sliding))
                      (not (have-free-move))
                      )
   )
   
  (:action push-block-into-water
   :parameters (?from ?to - location ?dir - direction ?blockto - location)
   :precondition (and (at ?from)
                      (block ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (MOVE-DIR ?to ?blockto ?dir)
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (not (chip-state slipping)) ;does this matter?
                      (water ?blockto)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (block ?to))
                      (dirt ?blockto)
                      (floor ?to)
                      (not (water ?blockto))
                      (not (chip-state sliding))
                      (not (have-free-move))
                      )
   )
   
   ;;these may be uinified into a single action?
  (:action push-block-into-bomb
   :parameters (?from ?to - location ?dir - direction ?blockto - location)
   :precondition (and (at ?from)
                      (block ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (MOVE-DIR ?to ?blockto ?dir)
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (not (chip-state slipping)) ;does this matter?
                      (bomb ?blockto)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (block ?to))
                      (floor ?blockto)
                      (floor ?to)
                      (not (bomb ?blockto))
                      (not (chip-state sliding))
                      (not (have-free-move))
                      )
   )
  
  (:action move-socket
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (socket ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (chips-left n0)
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (socket ?to))
                      (floor ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      )
   )

;; Slide/Force Floors
  (:action move-force
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (force-floor ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (not (chip-state slipping))
                      (not (has-boots slide))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (chip-state sliding)
                      (not (have-free-move))
                      )
   )

  (:action slide-force-wall
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (wall ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (slide-dir ?from ?dir)
                      (chip-state sliding) ;; maybe redundent
                      )
   :effect       (have-free-move)
   )

  (:action slide-force-force
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (force-floor ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (slide-dir ?from ?dir)
                      (chip-state sliding) ;; maybe redundent
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (have-free-move)
                      )
   )

  (:action move-force-force
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (force-floor ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (have-free-move)
                      (not (slide-dir ?from ?dir)) ;; if free move then don't go this way
                      (chip-state sliding) ;; maybe redundent
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (have-free-move))
                      )
   )

  (:action slide-force-floor
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (floor ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (slide-dir ?from ?dir)
                      (chip-state sliding) ;; maybe redundent
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      )
   )

  (:action move-force-floor
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (floor ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (not (slide-dir ?from ?dir)) ;; if free move then don't go this way
                      (have-free-move)
                      (chip-state sliding) ;; maybe redundent
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      )
   )

  (:action slide-force-boots
   :parameters (?from ?to - location ?dir - direction ?t - type)
   :precondition (and (at ?from)
                      (force-floor ?from)
                      (MOVE-DIR ?from ?to ?dir)
                      (slide-dir ?from ?dir)
                      (chip-state sliding) ;; maybe redundent
                      (boots ?to ?t)
                      ;; (not (has-boots ?t)) ;; wrong
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (have-free-move))
                      (not (boots ?to ?t))
                      (floor ?to)
                      (has-boots ?t)
                      (not (chip-state sliding))
                      )
   )

  (:action move-force-boots
   :parameters (?from ?to - location ?dir - direction ?t - type)
   :precondition (and (at ?from)
                      (force-floor ?from)
                      (MOVE-DIR ?from ?to ?dir)
                      (not (slide-dir ?from ?dir)) ;; if free move then don't go this way
                      (have-free-move)
                      (chip-state sliding) ;; maybe redundent
                      (boots ?to ?t)
                      ;; (not (has-boots ?t)) ;; wrong
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (have-free-move))
                      (not (boots ?to ?t))
                      (floor ?to)
                      (has-boots ?t)
                      (not (chip-state sliding))
                      )
   )

  (:action slide-force-chip
   :parameters (?from ?to - location ?dir - direction ?ochips ?nchips - number)
   :precondition (and (at ?from)
                      (force-floor ?from)
                      (MOVE-DIR ?from ?to ?dir)
                      (slide-dir ?from ?dir)
                      (chip-state sliding) ;; maybe redundent
                      (chip ?to) ;;chips stuff
                      (chips-left ?ochips)
                      (or (successor ?nchips ?ochips)
                          ;; handle having n0 chips
                          (and (= ?ochips ?nchips) (= ?ochips n0))
                          )
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (have-free-move))
                      (not (chip ?to))
                      (floor ?to)
                      (not (chips-left ?ochips))
                      (chips-left ?nchips)
                      (not (chip-state sliding))
                      )
   )

  (:action move-force-chip
   :parameters (?from ?to - location ?dir - direction ?ochips ?nchips - number)
   :precondition (and (at ?from)
                      (force-floor ?from)
                      (MOVE-DIR ?from ?to ?dir)
                      (not (slide-dir ?from ?dir)) ;; if free move then don't go this way
                      (have-free-move)
                      (chip-state sliding) ;; maybe redundent
                      (chip ?to) ;;chips stuff
                      (chips-left ?ochips)
                      (or (successor ?nchips ?ochips)
                          ;; handle having n0 chips
                          (and (= ?ochips ?nchips) (= ?ochips n0))
                          )
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (have-free-move))
                      (not (chip ?to))
                      (floor ?to)
                      (not (chips-left ?ochips))
                      (chips-left ?nchips)
                      (not (chip-state sliding))
                      )
   )


;; Ice
  (:action move-ice
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (ice ?to)
                      (not  (has-boots ice))
                      (MOVE-DIR ?from ?to ?dir)
                      (not (chip-state sliding))
                      (not (chip-state slipping))
                      (not (has-boots ice))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (chip-state slipping)
                      (slipping-dir ?dir)
                      )
   )

  (:action move-ice-wall
   :parameters (?from ?to - location ?odir ?ndir - direction)
   :precondition (and (at ?from)
                      (ice-wall ?to)
                      (ice-wall-dir ?to ?odir ?ndir)
                      (not  (has-boots ice))
                      (MOVE-DIR ?from ?to ?odir)
                      (not (chip-state sliding))
                      (not (chip-state slipping))
                      (not (has-boots ice))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (chip-state slipping)
                      (slipping-dir ?ndir)
                      )
   )

  (:action slide-force-ice
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (ice ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (slide-dir ?from ?dir)
                      (chip-state sliding) ;; maybe redundent
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (chip-state slipping)
                      (slipping-dir ?dir)
                      )
   )

  (:action slide-force-ice-wall
   :parameters (?from ?to - location ?odir ?ndir - direction)
   :precondition (and (at ?from)
                      (force-floor ?from)
                      (MOVE-DIR ?from ?to ?odir)
                      (slide-dir ?from ?odir)
                      (chip-state sliding) ;; maybe redundent
                      (ice-wall ?to)
                      (ice-wall-dir ?to ?odir ?ndir)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (chip-state slipping)
                      (slipping-dir ?ndir)
                      )
   )

  (:action slip-ice-ice
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (or (ice ?from) (ice-wall ?from))
                      (ice ?to)
                      (chip-state slipping)
                      (MOVE-DIR ?from ?to ?dir)
                      (slipping-dir ?dir)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      )
   )

  (:action slip-ice-force
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (or (ice ?from) (ice-wall ?from))
                      (force-floor ?to)
                      (chip-state slipping)
                      (MOVE-DIR ?from ?to ?dir)
                      (slipping-dir ?dir)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state slipping))
                      (not (slipping-dir ?dir))
                      (chip-state sliding)
                      )
   )

  (:action slip-ice-dirt
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (or (ice ?from) (ice-wall ?from))
                      (dirt ?to)
                      (chip-state slipping)
                      (MOVE-DIR ?from ?to ?dir)
                      (slipping-dir ?dir)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (socket ?to))
                      (floor ?to)
                      (not (chip-state slipping))
                      (not (slipping-dir ?dir))
                      )
   )

  (:action slip-ice-socket
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (or (ice ?from) (ice-wall ?from))
                      (socket ?to)
                      (chip-state slipping)
                      (MOVE-DIR ?from ?to ?dir)
                      (slipping-dir ?dir)
                      (chips-left n0)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (socket ?to))
                      (floor ?to)
                      (not (chip-state slipping))
                      (not (slipping-dir ?dir))
                      )
   )

  (:action slip-ice-ice-wall
   :parameters (?from ?to - location ?odir ?ndir - direction)
   :precondition (and (at ?from)
                      (or (ice ?from) (ice-wall ?from))
                      (ice-wall ?to)
                      (ice-wall-dir ?to ?odir ?ndir)
                      (chip-state slipping)
                      (MOVE-DIR ?from ?to ?odir)
                      (slipping-dir ?odir)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (slipping-dir ?odir))
                      (slipping-dir ?ndir)
                      )
   )

  (:action slip-ice-floor
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (floor ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (chip-state slipping)
                      (slipping-dir ?dir)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state slipping))
                      (not (slipping-dir ?dir))
                      )
   )

  (:action slip-ice-boots
   :parameters (?from ?to - location ?dir - direction ?t - type)
   :precondition (and (at ?from)
                      (boots ?to ?t)
                      ;; (not (has-boots ?t)) ;; wrong
                      (MOVE-DIR ?from ?to ?dir)
                      (chip-state slipping)
                      (slipping-dir ?dir)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (boots ?to ?t))
                      (floor ?to)
                      (not (chip-state slipping))
                      (not (slipping-dir ?dir))
                      (has-boots ?t)
                      )
   )

  (:action slip-ice-chip
   :parameters (?from ?to - location ?dir - direction ?ochips ?nchips - number)
   :precondition (and (at ?from)
                      (chip ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (chips-left ?ochips)
                      (or (successor ?nchips ?ochips)
                          ;; handle having n0 chips
                          (and (= ?ochips ?nchips) (= ?ochips n0))
                          )
                      (chip-state slipping)
                      (slipping-dir ?dir)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip ?to))
                      (floor ?to)
                      (not (chips-left ?ochips))
                      (chips-left ?nchips)
                      (not (chip-state slipping))
                      (not (slipping-dir ?dir))
                      )
   )

;; The switch walls
  (:action move-switch-wall-open
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (switch-wall-open ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (not (chip-state slipping))
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (switched-walls-open n0)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      )
   )

  (:action move-switch-wall-closed
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (switch-wall-closed ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (not (chip-state slipping))
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (not (switched-walls-open n0))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      )
   )

  (:action move-toggle-walls-open
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (green-button ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (not (chip-state slipping))
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (not (switched-walls-open n0))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      (switched-walls-open n0)
                      )
   )

  (:action move-toggle-walls-closed
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (green-button ?to)
                      (MOVE-DIR ?from ?to ?dir)
                      (not (chip-state slipping))
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (switched-walls-open n0)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      (not (switched-walls-open n0))
                      )
  )
   
  (:action slip-ice-switch-wall-open
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (switch-wall-open ?to)
                      (chip-state slipping)
                      (MOVE-DIR ?from ?to ?dir)
                      (slipping-dir ?dir)
                      (switched-walls-open n0)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state slipping))
                      (not (slipping-dir ?dir))
                      )
   )

  (:action slip-ice-switch-wall-closed
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (switch-wall-closed ?to)
                      (chip-state slipping)
                      (MOVE-DIR ?from ?to ?dir)
                      (slipping-dir ?dir)
                      (not (switched-walls-open n0))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state slipping))
                      (not (slipping-dir ?dir))
                      )
   )

  (:action slip-ice-toggle-walls-open
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (green-button ?to)
                      (chip-state slipping)
                      (MOVE-DIR ?from ?to ?dir)
                      (slipping-dir ?dir)
                      (not (switched-walls-open n0))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state slipping))
                      (not (slipping-dir ?dir))
                      (switched-walls-open n0)
                      )
   )

  (:action slip-ice-toggle-walls-closed
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (green-button ?to)
                      (chip-state slipping)
                      (MOVE-DIR ?from ?to ?dir)
                      (slipping-dir ?dir)
                      (switched-walls-open n0)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state slipping))
                      (not (slipping-dir ?dir))
                      (not (switched-walls-open n0))
                      )
  )
   
;; maybe make zero a succesor to itself
  (:action move-chip
   :parameters (?from ?to - location ?dir - direction ?ochips ?nchips - number)
   :precondition (and (at ?from)
                      (chip ?to)
                      (not (chip-state sliding))
                      (not (chip-state slipping))
                      (MOVE-DIR ?from ?to ?dir)
                      (chips-left ?ochips)
                      (or (successor ?nchips ?ochips)
                          ;; handle having n0 chips
                          (and (= ?ochips ?nchips) (= ?ochips n0))
                          )
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip ?to))
                      (floor ?to)
                      (not (chips-left ?ochips))
                      (chips-left ?nchips)
                      )
   )

;; Keys

;; Move to a tile containing a ?color key, having had ?okeys ?color keys already.
;; TODO Need to increase 'successor' numbers to accomodate large numbers of keys?
  (:action move-key
   :parameters (?from ?to - location ?dir - direction ?color - color ?okeys ?nkeys - number)
   :precondition (and (at ?from)
                      (key ?to ?color)
                      (MOVE-DIR ?from ?to ?dir)
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (not (chip-state slipping))
                      (has-keys ?color ?okeys)
                      (successor ?okeys ?nkeys)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      (not (key ?to ?color))
                      (floor ?to)
                      (not (has-keys ?color ?okeys))
                      (has-keys ?color ?nkeys)
                      )
   )

  (:action slide-force-key
   :parameters (?from ?to - location ?dir - direction ?color - color ?okeys ?nkeys - number)
   :precondition (and (at ?from)
                      (key ?to ?color)
                      (MOVE-DIR ?from ?to ?dir)
                      (slide-dir ?from ?dir)
                      (chip-state sliding) ;; maybe redundent
                      (has-keys ?color ?okeys)
                      (successor ?okeys ?nkeys)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      (not (key ?to ?color))
                      (floor ?to)
                      (not (has-keys ?color ?okeys))
                      (has-keys ?color ?nkeys)
                      )
   )

;; Move to a tile containing a ?color door, having ?okeys ?color keys already.
;; Need to indicate to the planner special :requirement to handle 
;; the '=' or 'when' such as 'adl?  See 'benchmarks/psr-large/domain.pddl'?
;; It seems not.
;; Should colors be 'constants' instead of 'objects'?  Seems to work the way it is.
  (:action move-door
   :parameters (?from ?to - location ?dir - direction ?color - color ?okeys ?nkeys - number)
   :precondition (and (at ?from)
                      (door ?to ?color)
                      (MOVE-DIR ?from ?to ?dir)
                      (not (chip-state slipping)) 
                      (or (not (chip-state sliding))
                          (not (slide-dir ?from ?dir)) ;; if free move then don't go this way
                          (have-free-move)
                          )
                      (has-keys ?color ?okeys)
                      (successor ?nkeys ?okeys)
                      (not (has-keys ?color n0))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      (not (door ?to ?color))
                      (floor ?to)
                      (when (not (= ?color green))
                        (and 
                          (not (has-keys ?color ?okeys))
                          (has-keys ?color ?nkeys))
                        )
                      )
   )

  (:action slide-force-door
   :parameters (?from ?to - location ?dir - direction ?color - color ?okeys ?nkeys - number)
   :precondition (and (at ?from)
                      (door ?to ?color)
                      (MOVE-DIR ?from ?to ?dir)
                      (chip-state sliding)
                      (slide-dir ?from ?dir)
                      (has-keys ?color ?okeys)
                      (successor ?nkeys ?okeys)
                      (not (has-keys ?color n0))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      (not (door ?to ?color))
                      (floor ?to)
                      (when (not (= ?color green))
                        (and 
                          (not (has-keys ?color ?okeys))
                          (has-keys ?color ?nkeys))
                        )
                      )
   )

  (:action slip-ice-door
   :parameters (?from ?to - location ?dir - direction ?color - color ?okeys ?nkeys - number)
   :precondition (and (at ?from)
                      (door ?to ?color)
                      (MOVE-DIR ?from ?to ?dir)
                      (chip-state slipping) 
                      (slipping-dir ?dir)
                      (has-keys ?color ?okeys)
                      (successor ?nkeys ?okeys)
                      (not (has-keys ?color n0))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state slipping))
                      (not (slipping-dir ?dir))
                      (not (chip-state sliding))
                      (not (have-free-move))
                      (not (door ?to ?color))
                      (floor ?to)
                      (when (not (= ?color green))
                        (and 
                          (not (has-keys ?color ?okeys))
                          (has-keys ?color ?nkeys))
                        )
                      )
   )


  (:action move-boots
   :parameters (?from ?to - location ?dir - direction ?t - type)
   :precondition (and (at ?from)
                      (boots ?to ?t)
                      ;; (not (has-boots ?t)) ;; wrong
                      (MOVE-DIR ?from ?to ?dir)
                      (not (chip-state slipping))
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state slipping))
                      (not (chip-state sliding))
                      (not (have-free-move))
                      (not (boots ?to ?t))
                      (floor ?to)
                      (has-boots ?t)
                      )
   )

  (:action walk-on-water
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (water ?to)
                      (has-boots water)
                      (MOVE-DIR ?from ?to ?dir)
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (not (chip-state slipping))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      )
   )

  (:action slip-walk-on-water
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (water ?to)
                      (has-boots water)
                      (chip-state slipping)
                      (MOVE-DIR ?from ?to ?dir)
                      (slipping-dir ?dir)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state slipping))
                      (not (slipping-dir ?dir))
                      )
   )

  (:action walk-on-fire
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (fire ?to)
                      (has-boots fire)
                      (MOVE-DIR ?from ?to ?dir)
                      (or (not (chip-state sliding))
                          (have-free-move)
                          )
                      (not (chip-state slipping))
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      (not (have-free-move))
                      )
   )

  (:action slip-walk-on-fire
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (fire ?to)
                      (has-boots fire)
                      (chip-state slipping)
                      (MOVE-DIR ?from ?to ?dir)
                      (slipping-dir ?dir)
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state slipping))
                      (not (slipping-dir ?dir))
                      )
   )

  (:action walk-on-ice
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (ice ?to)
                      (has-boots ice)
                      (MOVE-DIR ?from ?to ?dir)
                      ;; (not (chip-state sliding)) ;; maybe redundent
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state sliding))
                      )
   )

  (:action walk-on-force-floor
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (force-floor ?to)
                      (has-boots slide)
                      (MOVE-DIR ?from ?to ?dir)
                      (not (chip-state slipping))
                      (not (chip-state sliding)) ;; maybe redundent
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      )
   )

  (:action slip-walk-on-force-floor
   :parameters (?from ?to - location ?dir - direction)
   :precondition (and (at ?from)
                      (force-floor ?to)
                      (has-boots slide)
                      (chip-state slipping)
                      (MOVE-DIR ?from ?to ?dir)
                      (slipping-dir ?dir)
                      (not (chip-state sliding)) ;; maybe redundent
                      )
   :effect       (and (not (at ?from))
                      (at ?to)
                      (not (chip-state slipping))
                      (not (slipping-dir ?dir))
                      )
   )
)
